### PR TITLE
Remove extra spec directory (use testunit)

### PR DESCRIPTION
**Pull request by paulhenrich**
I just started looking at this again since CincyRB is coming up. I was going to add a test and suggest a refactor and noticed you have both a test directory & an unused spec directory, so I thought I'd start by removing rspec. 

Minitest is the new default in the next version of rails, but you can always keep using whatever testing library you like across upgrades.

### CODE REVIEW

**Comment by paulhenrich** [comment]
Failed build a result of the build now actually running the existing tests, and missing some environment variables.

success.

I'm going to add the environment variables it's complaining about to test.rb and see if that fixes it. If you upgrade to 4.1+ you can put all this stuff in [secrets.yml](http://guides.rubyonrails.org/4_1_release_notes.html#config-secrets-yml), which loads from your ENV in prod.

**Comment by robertlandreaux** [comment]
Thank you so much, Paul, for your contributions!  I look forward to looking at them closely tomorrow. Unfortunately, I have not worked on Gradejoy since the last meetup. I have been busy with my part time dev job lately. 


I will see you tomorrow night if you will be at the Ruby meetup!


Robert



rom:"Paul Henrich" <notifications@github.com>
Date:Mon, Mar 16, 2015 at 15:41
Subject:Re: [Gradejoy] Remove extra spec directory (use testunit) (#28)

Failed build a result of the build now actually running the existing tests, and missing some environment variables.

￼.

I'm going to add the environment variables it's complaining about to test.rb and see if that fixes it. If you upgrade to 4.1+ you can put all this stuff in secrets.yml, which loads from your ENV in prod.

**Comment by paulhenrich** [comment]
Closing per our conversation.

**Comment by robertlandreaux** [comment]
Thank you, Paul, for your help! Feel free to contribute more in the future.
Robert

**Pull request closed without merging**
